# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(default='hi', max_length=250),
        ),
    ]
